argument_specs:
  main:
    short_description: Add packages to custom repository
    description:
     - Determine versions already installed in aptly repository;
     - Run each tasks file provided by C(packages) to download the corresponding deb package in C(unarchive_path);
     - Add the downloaded deb packages to the repository;
     - Add local deb provided by C(files) to the repository.
    options:
      repository_name:
        type: "str"
        default: "focal-tp"
        description: "name of the aptly repository"
      unarchive_path:
        type: "str"
        default: '/tmp/aptly'
        description: "path where to download deb"
      packages:
        type: "dict"
        default: {}
        description: "list of packages and version to add to the repository"
      files:
        type: "list"
        default: []
        description: "list of package files to add to the repository"