galaxy_info:
  author: Julien Guillod <julien.guillod@sorbonne-universite.fr>
  description: Ansible role to add deb packages to a custom apt repository managed by aptly.
  company: Sorbonne University
  license: AGPL-3.0-only
  min_ansible_version: 2.11
  platforms:
  - name: Ubuntu
    versions: [all]
  - name: Debian
    versions: [all]
  galaxy_tags:
  - labs
  - tp
  - mathematics
  - su
  - aptly
  - vscodium
  - freefem
  - deaduction
  - rstudio
  - veyon
dependencies: []