- name: Install nginx
  apt:
    name: nginx
  become: true

- name: Add netboot to nginx configuration
  blockinfile:
    path: /etc/nginx/sites-available/default
    block: |2
      	location /ubuntu {
          autoindex on;
      		alias /var/aptly/public/ubuntu;
      	}
    insertbefore: '^}$'
    backup: true
    marker: "	# {mark} aptly block"
  become: true
  notify: reload nginx

- name: Open firewall port
  ufw:
    rule: allow
    port: http
    from_ip: "{{ item }}"
  become: true
  loop: "{{ allowed_ips | default(['any']) }}"