- name: First gather facts if nothing in cache
  block:
    - name: Wait for SSH to be ready
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        search_regex: OpenSSH
      vars:
          ansible_connection: local
      #when: false

    - name: Add remote SSH fingerprint to server's known_hosts
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t ecdsa ' + inventory_hostname) }}"
      delegate_to: localhost
      when: false

    - name: Gathering facts
      setup:
  when: "'hostname' not in ansible_facts"

- name: Initial setup
  import_tasks: "initial.yml"

- name: Modify machine ID
  import_tasks: "machine_id.yml"

- name: Setup netplan
  import_tasks: "netplan.yml"

- name: Flush handlers
  meta: flush_handlers

- name: Define proxy
  import_tasks: "proxy.yml"
  when: proxy_env is defined

- name: Customize
  import_tasks: "custom.yml"

- name: Define custom repository
  import_tasks: "repository.yml"