- name: Add proxy
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item }}="
    line: '{{ item }}="{{ proxy_env[item] }}"'
  with_items: "{{ proxy_env }}"
  become: true
  when: proxy_env is defined

- name: Remove proxy set by preseed in apt.conf
  file:
    path: /etc/apt/apt.conf
    state: absent
  become: true

- name: Add proxy for apt
  lineinfile:
    dest: /etc/apt/apt.conf.d/01proxy
    regexp: '^Acquire::http::Proxy'
    create: yes
    state: present
    line: 'Acquire::http::Proxy "{{ http_proxy }}";'
  vars:
    - http_proxy: "{{ proxy_env['http_proxy'] }}"
  become: true
  when: proxy_env is defined